# ManageServer 配置文件

# 消息配置
messages:
  prefix: "&7[&6ManageServer&7] "
  player-join: "&e%player% &a加入了服务器"
  player-quit: "&e%player% &c离开了服务器"
  player-first-join: "&e欢迎 &b%player% &e首次加入服务器!"
  player-banned: "&c玩家 &e%player% &c已被封禁，原因: &e%reason%"
  player-unbanned: "&a玩家 &e%player% &a已被解封"
  player-kicked: "&c玩家 &e%player% &c已被踢出，原因: &e%reason%"
  ban-message: "&c你已被服务器封禁!\n&c原因: &e%reason%\n&c如有异议，请联系管理员"
  kick-message: "&c你已被服务器踢出!\n&c原因: &e%reason%"
  
# 功能设置
features:
  welcome-message: true
  quit-message: true
  broadcast-ban: true
  broadcast-kick: true

# OneBot配置
onebot:
  # 是否启用OneBot功能
  enabled: false
  # 连接方式: http 或 websocket
  connection-type: websocket
  # HTTP连接配置 (当connection-type为http时使用)
  http:
    url: "http://127.0.0.1:5700"
    access-token: ""
  # WebSocket连接配置 (当connection-type为websocket时使用)
  websocket:
    url: "ws://127.0.0.1:6700"
    access-token: ""
  # 消息转发配置
  forward:
    # 服务器消息转发到QQ群
    server-to-qq: true
    # QQ消息转发到服务器
    qq-to-server: true
    # 玩家加入/退出消息转发到QQ
    player-join-quit: true
    # 封禁/踢出消息转发到QQ
    ban-kick: true
  # QQ群配置
  groups:
    # 主群ID
    main-group: 123456789
    # 管理群ID (可选)
    admin-group: 987654321
  # QQ用户与Minecraft玩家绑定
  bindings:
    # 格式: QQ号: 玩家名
    123456789: "ExamplePlayer"
  # 命令前缀 (用于在QQ中执行Minecraft命令)
  command-prefix: "!" 